# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Azure Devops SP'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd website
    npm install
    npm run build
    find ./build
  displayName: 'npm install and build'

- script: |
    docker run --rm \
        --volume="$PWD/website:/website" \
        --volume="$PWD/bin:/tmp/bin" \
        mcr.microsoft.com/azure-cli /bin/bash /tmp/bin/publish-website.sh
  displayName: Run Az CLI container
  env:
    SP_APPID: $(AppId)
    SP_PASS: $(Password)
    SP_NAME: $(Name)
    SP_TENANT: $(Tenant)
