# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Azure Devops SP'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd website
    npm install
    npm run build
    find ./build
  displayName: 'npm install and build'

- script: |
    docker run --rm \
        --volume="$PWD/website:/website" \
        --volume=${HOME}/.ssh:/root/.ssh \
        mcr.microsoft.com/azure-cli find /website/build
  displayName: Run Az CLI container

- script: |
    docker build -t $DOCKER_USER/$(imageName):$(setVar.commitHash) -t $DOCKER_USER/$(imageName):latest .
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    docker push $DOCKER_USER/$(imageName):$(setVar.commitHash)
    docker push $DOCKER_USER/$(imageName):latest
  displayName: Build Docker container
  env:
    DOCKER_PASSWORD: $(docker_pass)
    DOCKER_USER: $(docker_user)